name: Frontend Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to Azure Storage
      uses: azure/CLI@v1

    - name: Deploy to Static Website
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS }}
        az storage blob upload-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --destination \$web \
          --source ./ \
          --overwrite \
          --auth-mode key
